=== SimoneMagagna/Scuola-delle-Nove-Armonie-Conselve/public_html/data/immagini.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns="http://www.9armonie.com/immagini"
		   targetNamespace="http://www.9armonie.com/immagini"
		   elementFormDefault="qualified">

	<xs:element name="immagini" type="TipoImmagini"/>

	<xs:complexType name="TipoImmagini">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<xs:element name="immagine" type="TipoImmagine"/>
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="TipoImmagine">
		<xs:sequence>
			<xs:element name="src" type="xs:anyURI"/>
			<xs:element name="src_small" type="xs:anyURI"/>
			<xs:element name="alt" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== SimoneMagagna/Scuola-delle-Nove-Armonie-Conselve/public_html/data/immagini.xml
<?xml version="1.0"?>
<immagini xmlns="http://www.9armonie.com/immagini" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.9armonie.com/immagini immagini.xsd">
    <immagine>
        <src>../Foto/colpitori1@big.jpg</src>
        <src_small>../Foto/colpitori1.jpg</src_small>
        <alt> </alt>
    </immagine>
    <immagine>
        <src>../Foto/colpitori2@big.jpg</src>
        <src_small>../Foto/colpitori2.jpg</src_small>
        <alt> </alt>
    </immagine>
	<immagine>
		<src>../Foto/StageTaiChiMare@big.jpg</src>
		<src_small>../Foto/StageTaiChiMare.jpg</src_small>
		<alt>dfghj</alt>
	</immagine>
</immagini>
