=== SimoneMagagna/Scuola-delle-Nove-Armonie-Conselve/public_html/data/news.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns="http://www.9armonie.com/news"
		   xmlns:n="http://www.9armonie.com/news"
    targetNamespace="http://www.9armonie.com/news"
    elementFormDefault="qualified">

	<xs:element name="notizie" type= "TipoNotizie">
		<xs:unique name="uniqueId">
			<xs:selector xpath="n:news" />
			<xs:field xpath="@id" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="TipoNotizie">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="news" type= "TipoNotizia" />
		</xs:sequence>
		<xs:attribute name="nextid" type="xs:positiveInteger" default="1"/>
	</xs:complexType>

	<xs:complexType name= "TipoNotizia">
		<xs:sequence>
			<xs:element name="data" type="xs:date" />
			<xs:element name="ora" type="xs:time" />
			<xs:element name="titolo" type= "xs:string" />
			<xs:element name="descrizione" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
	</xs:complexType>

</xs:schema>

=== SimoneMagagna/Scuola-delle-Nove-Armonie-Conselve/public_html/data/news.xml
<?xml version="1.0"?>
<notizie xmlns="http://www.9armonie.com/news" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.9armonie.com/news news.xsd" nextid="5">
    <news id="1">
        <data>2014-12-18</data>
        <ora>12:00:00</ora>
        <titolo>Sito in costruzione</titolo>
        <descrizione>Sito sviluppato per il progetto di Tecnologie Web dell'Universit&#xE0; degli Studi di Padova</descrizione>
    </news>
    <news id="2">
        <data>2014-12-18</data>
        <ora>12:00:00</ora>
        <titolo>News</titolo>
        <descrizione>Sono una news di prova</descrizione>
    </news>
    <news id="3">
        <data>2014-12-19</data>
        <ora>12:00:00</ora>
        <titolo>Terza news</titolo>
        <descrizione>Sono una notizia di prova</descrizione>
    </news>
	<news id="4">
		<data>2015-01-31</data>
		<ora>19:34:33</ora>
		<titolo>Buon Anno</titolo>
		<descrizione>La scuola delle 9 Armonie di Conselve coglie l'occasione per auguare a tutti gli iscritti un felice anno nuovo.</descrizione>
	</news>
</notizie>
