=== SimoneMagagna/Scuola-delle-Nove-Armonie-Conselve/public_html/data/utenti.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns="http://www.9armonie.com/utenti"
    xmlns:u="http://www.9armonie.com/utenti"
    targetNamespace="http://www.9armonie.com/utenti"
    elementFormDefault="qualified">

<xs:element name="utenti" type="TipoUtenti">
	<xs:unique name="uniqueId">
		<xs:selector xpath="u:utente" />
		<xs:field xpath="@id" />
	</xs:unique>
	<xs:unique name="uniqueEmail">
		<xs:selector xpath="u:utente" />
		<xs:field xpath="u:email" />
	</xs:unique>
</xs:element>
	
<xs:complexType name="TipoUtenti">
	<xs:sequence minOccurs="0" maxOccurs="unbounded">
		<xs:element name="utente" type= "TipoUtente"/>
	</xs:sequence>
	<xs:attribute name="nextid" type="xs:positiveInteger" default="1"/>
</xs:complexType>

<xs:complexType name="TipoUtente">
	<xs:sequence>
		<xs:element name="nome" type="xs:string" />
		<xs:element name="cognome" type="xs:string" />
		<xs:element name="email" type="TipoEmail"/>
		<xs:element name="password" type="xs:string" />
	</xs:sequence>
	<xs:attribute name="amministratore" type="xs:boolean" default="false"/>
	<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
</xs:complexType>

<xs:simpleType name= "TipoEmail">
	<xs:restriction base= "xs:string">
		<xs:pattern value= "[^@]+@[^\.]+\..+" />
	</xs:restriction>
</xs:simpleType>	

</xs:schema>

=== SimoneMagagna/Scuola-delle-Nove-Armonie-Conselve/public_html/data/utenti.xml
<?xml version="1.0"?>
<utenti xmlns="http://www.9armonie.com/utenti" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.9armonie.com/utenti utenti.xsd" nextid="3">
    <utente amministratore="true" id="1">
        <nome>Giacomo </nome>
        <cognome>Manzoli</cognome>
        <email>giacomo.manzoli@gmail.com</email>
        <password>1234</password>
    </utente>
<utente amministratore="true" id="2">
		<nome>Simone</nome>
		<cognome>Magana</cognome>
		<email>simone@9armonie.it</email>
		<password>asdasd</password>
	</utente>
</utenti>
